-- Adopt existing hosted schema drift without deleting data or enabling deferred features.
BEGIN;
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS picture_url TEXT;

CREATE TABLE IF NOT EXISTS public.ai_conversations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    title text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_favorite boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS public.ai_entitlements (
    user_id uuid NOT NULL,
    tier text DEFAULT 'free'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ai_entitlements_tier_check CHECK ((tier = ANY (ARRAY['free'::text, 'pro'::text, 'premium'::text])))
);

CREATE TABLE IF NOT EXISTS public.ai_free_message_credits (
    user_id uuid NOT NULL,
    lifetime_free_used integer DEFAULT 0 NOT NULL,
    rewarded_ad_credits integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ai_free_message_credits_lifetime_free_used_check CHECK ((lifetime_free_used >= 0)),
    CONSTRAINT ai_free_message_credits_rewarded_ad_credits_check CHECK ((rewarded_ad_credits >= 0))
);

CREATE TABLE IF NOT EXISTS public.ai_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    conversation_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    model_used text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ai_messages_role_check CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])))
);

CREATE TABLE IF NOT EXISTS public.ai_rewarded_ad_grants (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    credits_granted integer DEFAULT 10 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ai_rewarded_ad_grants_credits_granted_check CHECK ((credits_granted > 0))
);

CREATE TABLE IF NOT EXISTS public.ai_usage (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    usage_date date DEFAULT CURRENT_DATE NOT NULL,
    tier text DEFAULT 'free'::text NOT NULL,
    model_used text NOT NULL,
    input_tokens integer DEFAULT 0 NOT NULL,
    output_tokens integer DEFAULT 0 NOT NULL,
    total_tokens integer DEFAULT 0 NOT NULL,
    request_count integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ai_usage_tier_check CHECK ((tier = ANY (ARRAY['free'::text, 'pro'::text, 'premium'::text])))
);

CREATE TABLE IF NOT EXISTS public.ai_usage_reservations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    usage_date date DEFAULT CURRENT_DATE NOT NULL,
    tier text NOT NULL,
    status text DEFAULT 'reserved'::text NOT NULL,
    free_credit_source text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ai_usage_reservations_free_credit_source_check CHECK ((free_credit_source = ANY (ARRAY['lifetime'::text, 'rewarded'::text]))),
    CONSTRAINT ai_usage_reservations_status_check CHECK ((status = ANY (ARRAY['reserved'::text, 'succeeded'::text, 'failed'::text, 'refunded'::text]))),
    CONSTRAINT ai_usage_reservations_tier_check CHECK ((tier = ANY (ARRAY['free'::text, 'pro'::text, 'premium'::text])))
);

CREATE TABLE IF NOT EXISTS public.test (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text
);

DO $adopt$ BEGIN IF to_regclass('public.test_id_seq') IS NULL THEN
ALTER TABLE public.test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_conversations'::regclass AND conname='ai_conversations_pkey') THEN
ALTER TABLE ONLY public.ai_conversations
    ADD CONSTRAINT ai_conversations_pkey PRIMARY KEY (id);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_entitlements'::regclass AND conname='ai_entitlements_pkey') THEN
ALTER TABLE ONLY public.ai_entitlements
    ADD CONSTRAINT ai_entitlements_pkey PRIMARY KEY (user_id);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_free_message_credits'::regclass AND conname='ai_free_message_credits_pkey') THEN
ALTER TABLE ONLY public.ai_free_message_credits
    ADD CONSTRAINT ai_free_message_credits_pkey PRIMARY KEY (user_id);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_messages'::regclass AND conname='ai_messages_pkey') THEN
ALTER TABLE ONLY public.ai_messages
    ADD CONSTRAINT ai_messages_pkey PRIMARY KEY (id);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_rewarded_ad_grants'::regclass AND conname='ai_rewarded_ad_grants_pkey') THEN
ALTER TABLE ONLY public.ai_rewarded_ad_grants
    ADD CONSTRAINT ai_rewarded_ad_grants_pkey PRIMARY KEY (id);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_usage'::regclass AND conname='ai_usage_pkey') THEN
ALTER TABLE ONLY public.ai_usage
    ADD CONSTRAINT ai_usage_pkey PRIMARY KEY (id);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_usage_reservations'::regclass AND conname='ai_usage_reservations_pkey') THEN
ALTER TABLE ONLY public.ai_usage_reservations
    ADD CONSTRAINT ai_usage_reservations_pkey PRIMARY KEY (id);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.test'::regclass AND conname='test_pkey') THEN
ALTER TABLE ONLY public.test
    ADD CONSTRAINT test_pkey PRIMARY KEY (id);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF to_regclass('public.ai_conversations_user_id_is_favorite_updated_at_idx') IS NULL THEN
CREATE INDEX ai_conversations_user_id_is_favorite_updated_at_idx ON public.ai_conversations USING btree (user_id, is_favorite, updated_at DESC);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF to_regclass('public.ai_conversations_user_id_updated_at_idx') IS NULL THEN
CREATE INDEX ai_conversations_user_id_updated_at_idx ON public.ai_conversations USING btree (user_id, updated_at DESC);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF to_regclass('public.ai_messages_conversation_id_created_at_idx') IS NULL THEN
CREATE INDEX ai_messages_conversation_id_created_at_idx ON public.ai_messages USING btree (conversation_id, created_at);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF to_regclass('public.ai_messages_user_id_created_at_idx') IS NULL THEN
CREATE INDEX ai_messages_user_id_created_at_idx ON public.ai_messages USING btree (user_id, created_at);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF to_regclass('public.ai_rewarded_ad_grants_user_id_created_at_idx') IS NULL THEN
CREATE INDEX ai_rewarded_ad_grants_user_id_created_at_idx ON public.ai_rewarded_ad_grants USING btree (user_id, created_at DESC);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF to_regclass('public.ai_usage_reservations_user_id_tier_usage_date_status_idx') IS NULL THEN
CREATE INDEX ai_usage_reservations_user_id_tier_usage_date_status_idx ON public.ai_usage_reservations USING btree (user_id, tier, usage_date, status);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF to_regclass('public.ai_usage_reservations_user_id_usage_date_status_idx') IS NULL THEN
CREATE INDEX ai_usage_reservations_user_id_usage_date_status_idx ON public.ai_usage_reservations USING btree (user_id, usage_date, status);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF to_regclass('public.ai_usage_user_id_model_used_usage_date_idx') IS NULL THEN
CREATE INDEX ai_usage_user_id_model_used_usage_date_idx ON public.ai_usage USING btree (user_id, model_used, usage_date);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF to_regclass('public.ai_usage_user_id_usage_date_idx') IS NULL THEN
CREATE INDEX ai_usage_user_id_usage_date_idx ON public.ai_usage USING btree (user_id, usage_date);
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='public.ai_conversations'::regclass AND tgname='set_updated_at_ai_conversations') THEN
CREATE TRIGGER set_updated_at_ai_conversations BEFORE UPDATE ON public.ai_conversations FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='public.ai_entitlements'::regclass AND tgname='set_updated_at_ai_entitlements') THEN
CREATE TRIGGER set_updated_at_ai_entitlements BEFORE UPDATE ON public.ai_entitlements FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='public.ai_free_message_credits'::regclass AND tgname='set_updated_at_ai_free_message_credits') THEN
CREATE TRIGGER set_updated_at_ai_free_message_credits BEFORE UPDATE ON public.ai_free_message_credits FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='public.ai_usage_reservations'::regclass AND tgname='set_updated_at_ai_usage_reservations') THEN
CREATE TRIGGER set_updated_at_ai_usage_reservations BEFORE UPDATE ON public.ai_usage_reservations FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_conversations'::regclass AND conname='ai_conversations_user_id_fkey') THEN
ALTER TABLE ONLY public.ai_conversations
    ADD CONSTRAINT ai_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_entitlements'::regclass AND conname='ai_entitlements_user_id_fkey') THEN
ALTER TABLE ONLY public.ai_entitlements
    ADD CONSTRAINT ai_entitlements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_free_message_credits'::regclass AND conname='ai_free_message_credits_user_id_fkey') THEN
ALTER TABLE ONLY public.ai_free_message_credits
    ADD CONSTRAINT ai_free_message_credits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_messages'::regclass AND conname='ai_messages_conversation_id_fkey') THEN
ALTER TABLE ONLY public.ai_messages
    ADD CONSTRAINT ai_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.ai_conversations(id) ON DELETE CASCADE;
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_messages'::regclass AND conname='ai_messages_user_id_fkey') THEN
ALTER TABLE ONLY public.ai_messages
    ADD CONSTRAINT ai_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_rewarded_ad_grants'::regclass AND conname='ai_rewarded_ad_grants_user_id_fkey') THEN
ALTER TABLE ONLY public.ai_rewarded_ad_grants
    ADD CONSTRAINT ai_rewarded_ad_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_usage_reservations'::regclass AND conname='ai_usage_reservations_user_id_fkey') THEN
ALTER TABLE ONLY public.ai_usage_reservations
    ADD CONSTRAINT ai_usage_reservations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
END IF; END; $adopt$;

DO $adopt$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.ai_usage'::regclass AND conname='ai_usage_user_id_fkey') THEN
ALTER TABLE ONLY public.ai_usage
    ADD CONSTRAINT ai_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
END IF; END; $adopt$;

ALTER TABLE public.ai_conversations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_conversations FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.ai_conversations TO service_role;

ALTER TABLE public.ai_entitlements ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_entitlements FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.ai_entitlements TO service_role;

ALTER TABLE public.ai_free_message_credits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_free_message_credits FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.ai_free_message_credits TO service_role;

ALTER TABLE public.ai_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_messages FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.ai_messages TO service_role;

ALTER TABLE public.ai_rewarded_ad_grants ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_rewarded_ad_grants FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.ai_rewarded_ad_grants TO service_role;

ALTER TABLE public.ai_usage ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_usage FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.ai_usage TO service_role;

ALTER TABLE public.ai_usage_reservations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ai_usage_reservations FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.ai_usage_reservations TO service_role;

ALTER TABLE public.test ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.test FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.test TO service_role;
REVOKE ALL ON SEQUENCE public.test_id_seq FROM PUBLIC, anon, authenticated;
GRANT ALL ON SEQUENCE public.test_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.complete_player_ai_message_reservation(p_user_id uuid, p_reservation_id uuid, p_success boolean)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  reservation_row public.ai_usage_reservations%ROWTYPE;
BEGIN
  IF auth.uid() IS NULL OR auth.uid() <> p_user_id THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  SELECT *
  INTO reservation_row
  FROM public.ai_usage_reservations
  WHERE id = p_reservation_id
    AND user_id = p_user_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  IF reservation_row.status <> 'reserved' THEN
    RETURN true;
  END IF;

  IF p_success THEN
    UPDATE public.ai_usage_reservations
    SET status = 'succeeded',
        updated_at = now()
    WHERE id = p_reservation_id
      AND user_id = p_user_id;

    RETURN true;
  END IF;

  IF reservation_row.tier = 'free' THEN
    IF reservation_row.free_credit_source = 'lifetime' THEN
      UPDATE public.ai_free_message_credits
      SET lifetime_free_used = greatest(lifetime_free_used - 1, 0),
          updated_at = now()
      WHERE user_id = p_user_id;
    ELSIF reservation_row.free_credit_source = 'rewarded' THEN
      UPDATE public.ai_free_message_credits
      SET rewarded_ad_credits = rewarded_ad_credits + 1,
          updated_at = now()
      WHERE user_id = p_user_id;
    END IF;

    UPDATE public.ai_usage_reservations
    SET status = 'refunded',
        updated_at = now()
    WHERE id = p_reservation_id
      AND user_id = p_user_id;

    RETURN true;
  END IF;

  UPDATE public.ai_usage_reservations
  SET status = 'failed',
      updated_at = now()
  WHERE id = p_reservation_id
    AND user_id = p_user_id;

  RETURN true;
END;
$function$
;
REVOKE ALL ON FUNCTION public.complete_player_ai_message_reservation(uuid,uuid,boolean) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.complete_player_ai_message_reservation(uuid,uuid,boolean) TO service_role;

CREATE OR REPLACE FUNCTION public.consume_player_ai_free_message(p_user_id uuid, p_lifetime_limit integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  credit_row public.ai_free_message_credits%ROWTYPE;
BEGIN
  IF auth.uid() IS NULL OR auth.uid() <> p_user_id THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  INSERT INTO public.ai_free_message_credits (user_id)
  VALUES (p_user_id)
  ON CONFLICT (user_id) DO NOTHING;

  SELECT *
  INTO credit_row
  FROM public.ai_free_message_credits
  WHERE user_id = p_user_id
  FOR UPDATE;

  IF credit_row.lifetime_free_used < p_lifetime_limit THEN
    UPDATE public.ai_free_message_credits
    SET lifetime_free_used = lifetime_free_used + 1,
        updated_at = now()
    WHERE user_id = p_user_id;

    RETURN true;
  END IF;

  IF credit_row.rewarded_ad_credits > 0 THEN
    UPDATE public.ai_free_message_credits
    SET rewarded_ad_credits = rewarded_ad_credits - 1,
        updated_at = now()
    WHERE user_id = p_user_id;

    RETURN true;
  END IF;

  RETURN false;
END;
$function$
;
REVOKE ALL ON FUNCTION public.consume_player_ai_free_message(uuid,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_player_ai_free_message(uuid,integer) TO service_role;

CREATE OR REPLACE FUNCTION public.reserve_player_ai_message(p_user_id uuid, p_tier text, p_free_lifetime_limit integer, p_daily_limit integer)
 RETURNS TABLE(reservation_id uuid, allowed boolean, code text, limit_value integer, used_count integer, remaining_count integer, rewarded_ad_credits integer, free_credit_source text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  credit_row public.ai_free_message_credits%ROWTYPE;
  current_used INTEGER := 0;
  current_remaining INTEGER := 0;
  next_reservation_id UUID;
  consumed_source TEXT;
BEGIN
  IF auth.uid() IS NULL OR auth.uid() <> p_user_id THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  IF p_tier NOT IN ('free', 'pro', 'premium') THEN
    RAISE EXCEPTION 'Invalid tier';
  END IF;

  IF p_tier = 'free' THEN
    INSERT INTO public.ai_free_message_credits (user_id)
    VALUES (p_user_id)
    ON CONFLICT (user_id) DO NOTHING;

    SELECT *
    INTO credit_row
    FROM public.ai_free_message_credits
    WHERE user_id = p_user_id
    FOR UPDATE;

    current_remaining :=
      greatest(p_free_lifetime_limit - credit_row.lifetime_free_used, 0)
      + credit_row.rewarded_ad_credits;

    IF current_remaining <= 0 THEN
      RETURN QUERY SELECT
        NULL::UUID,
        false,
        'free_limit_reached',
        p_free_lifetime_limit,
        credit_row.lifetime_free_used,
        0,
        credit_row.rewarded_ad_credits,
        NULL::TEXT;
      RETURN;
    END IF;

    IF credit_row.lifetime_free_used < p_free_lifetime_limit THEN
      consumed_source := 'lifetime';

      UPDATE public.ai_free_message_credits
      SET lifetime_free_used = lifetime_free_used + 1,
          updated_at = now()
      WHERE user_id = p_user_id;
    ELSE
      consumed_source := 'rewarded';

      UPDATE public.ai_free_message_credits
      SET rewarded_ad_credits = greatest(ai_free_message_credits.rewarded_ad_credits - 1, 0),
          updated_at = now()
      WHERE user_id = p_user_id;
    END IF;

    INSERT INTO public.ai_usage_reservations (user_id, tier, status, free_credit_source)
    VALUES (p_user_id, p_tier, 'reserved', consumed_source)
    RETURNING id INTO next_reservation_id;

    SELECT *
    INTO credit_row
    FROM public.ai_free_message_credits
    WHERE user_id = p_user_id;

    current_remaining :=
      greatest(p_free_lifetime_limit - credit_row.lifetime_free_used, 0)
      + credit_row.rewarded_ad_credits;

    RETURN QUERY SELECT
      next_reservation_id,
      true,
      'reserved',
      p_free_lifetime_limit,
      credit_row.lifetime_free_used,
      current_remaining,
      credit_row.rewarded_ad_credits,
      consumed_source;
    RETURN;
  END IF;

  IF p_daily_limit <= 0 THEN
    RAISE EXCEPTION 'Invalid daily limit';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext(p_user_id::TEXT || ':' || current_date::TEXT || ':' || p_tier));

  SELECT count(*)::INTEGER
  INTO current_used
  FROM public.ai_usage_reservations
  WHERE user_id = p_user_id
    AND usage_date = current_date
    AND tier = p_tier
    AND status IN ('reserved', 'succeeded');

  IF current_used >= p_daily_limit THEN
    RETURN QUERY SELECT
      NULL::UUID,
      false,
      'daily_limit_reached',
      p_daily_limit,
      current_used,
      0,
      NULL::INTEGER,
      NULL::TEXT;
    RETURN;
  END IF;

  INSERT INTO public.ai_usage_reservations (user_id, tier, status)
  VALUES (p_user_id, p_tier, 'reserved')
  RETURNING id INTO next_reservation_id;

  RETURN QUERY SELECT
    next_reservation_id,
    true,
    'reserved',
    p_daily_limit,
    current_used + 1,
    greatest(p_daily_limit - current_used - 1, 0),
    NULL::INTEGER,
    NULL::TEXT;
END;
$function$
;
REVOKE ALL ON FUNCTION public.reserve_player_ai_message(uuid,text,integer,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_player_ai_message(uuid,text,integer,integer) TO service_role;

NOTIFY pgrst, 'reload schema';
COMMIT;
